name: env
description: "prepare actions env"

runs:
  using: "composite"

  steps:
    - name: import env variables
      shell: bash
      run: cat ".github/env" >> $GITHUB_ENV

    - name: setup go version
      uses: actions/setup-go@v4
      with:
        check-latest: true
        go-version:
          ${{ env.-version }}