name: add label

on:
  issue_comment:
    types: [created]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.comment.body, '/feature') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            type/feature
